import com.github.spotbugs.snom.Confidence
import com.github.spotbugs.snom.Effort
import com.github.spotbugs.snom.SpotBugsTask

plugins {
    id 'groovy'
    id 'codenarc'
    id 'com.github.spotbugs' version '6.5.9'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation localGroovy()
}

sourceSets {
    main {
        groovy {
            srcDirs = ['vars']
        }
    }
}

codenarc {
    toolVersion = '3.6.0'
    configFile = file('config/codenarc/rules.xml')
    ignoreFailures = false
    maxPriority1Violations = 0
    maxPriority2Violations = 0
    maxPriority3Violations = 0
}

tasks.named('codenarcMain') {
    source = fileTree('vars') {
        include '**/*.groovy'
    }

    reports {
        html.required = true
        html.outputLocation = layout.buildDirectory.file(
            'reports/codenarc/main.html'
        )

        text.required = true
        text.outputLocation = layout.buildDirectory.file(
            'reports/codenarc/main.txt'
        )
    }
}

spotbugs {
    ignoreFailures = false
    showStackTraces = true
    showProgress = true

    effort = Effort.valueOf('MAX')
    reportLevel = Confidence.valueOf('LOW')

    excludeFilter = file('config/spotbugs/exclude.xml')
}

tasks.named('spotbugsMain', SpotBugsTask) {
    reports {
        html.required = true
        html.outputLocation = layout.buildDirectory.file(
            'reports/spotbugs/main.html'
        )

        xml.required = true
        xml.outputLocation = layout.buildDirectory.file(
            'reports/spotbugs/main.xml'
        )
    }
}